services:
  mosquitto:
    container_name: mqtt
    image: eclipse-mosquitto
    restart: unless-stopped
    ports:
      - 1883:1883
      - 9001:9001
    volumes:
      - ./config:/mosquitto/config/
      - ./config/data:/mosquitto/data/
      - ./config/log:/mosquitto/log/
